test-and-build:
    stage: build
    image: golang:latest
    timeout: 10 minutes
    before_script:
        - mkdir -p ~/.config/ripntag
        - echo $DISCOGS_TOKEN > ~/.config/ripntag/token
        - apt install ffmpeg libtagc0-dev
    script:
        - go test -v ./...
        - go build -v -o ripntag cmd/ripntag/main.go

